Update mypipeline.yaml

diff --git a/.jfrog-pipelines/mypipeline.yaml b/.jfrog-pipelines/mypipeline.yaml
--- a/.jfrog-pipelines/mypipeline.yaml
+++ b/.jfrog-pipelines/mypipeline.yaml
@@ -72,6 +72,17 @@ pipelines:
           - ls -la workspace/upload
           - ls -la workspace/run_state
           - pwd
+          - WRAPPER_VERSION=$( `curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1` )
+          - echo '[INFO] ------------------------------------------------------------------------'
+          - echo '[INFO] DOWNLOADING VERACODE JAVA WRAPPER'
+          - | 
+            if [ `wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar` ]; then
+                  chmod 755 VeracodeJavaAPI.jar
+                  echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
+            else
+                  echo '[ERROR] DOWNLOAD FAILED'
+                  exit 1
+            fi
         onFailure:
           - echo "failed"
           # attempting to upload
