Update mypipeline.yaml

diff --git a/.jfrog-pipelines/mypipeline.yaml b/.jfrog-pipelines/mypipeline.yaml
--- a/.jfrog-pipelines/mypipeline.yaml
+++ b/.jfrog-pipelines/mypipeline.yaml
@@ -1,10 +1,10 @@
 valuesFilePath: ./values.yml
-#resources:
-  #- name: mvn_repo
-    #type: GitRepo
-    #configuration:
-      #path: {{ .Values.repoPath }}
-      #gitProvider: {{ .Values.gitProvider }}
+resources:
+  - name: mvn_repo
+    type: GitRepo
+    configuration:
+      path: "bnreplah/verademo" # {{ .Values.repoPath }}
+      gitProvider: "GitHub" # {{ .Values.gitProvider }}
 
 pipelines:
 - name: Verademo_hello_world
@@ -16,19 +16,19 @@ pipelines:
           - echo "onStart can be used to do some setup or initialization of your dependencies to prepare for the execution.
           - echo "Downloading the latest version of the Veracode Java API Wrapper"
           - mvn --version
-          - WRAPPER_VERSION=`curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1`
-          - echo '[INFO] ------------------------------------------------------------------------'
-          - echo '[INFO] DOWNLOADING VERACODE JAVA WRAPPER'
-          - >- 
-            if [ `wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar` ]; then
-                  chmod 755 VeracodeJavaAPI.jar
-                  echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
-            else
-                  echo '[ERROR] DOWNLOAD FAILED'
-                  exit 1
-            fi
-          - echo '[INFO] ------------------------------------------------------------------------'
-          - echo '[INFO] VERACODE UPLOAD AND SCAN'
+          #- WRAPPER_VERSION=`curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1`
+          #- echo '[INFO] ------------------------------------------------------------------------'
+          #- echo '[INFO] DOWNLOADING VERACODE JAVA WRAPPER'
+          #- >- 
+          #  if [ `wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar` ]; then
+          #        chmod 755 VeracodeJavaAPI.jar
+          #        echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
+          #  else
+          #        echo '[ERROR] DOWNLOAD FAILED'
+          #        exit 1
+          #  fi
+          #- echo '[INFO] ------------------------------------------------------------------------'
+          #- echo '[INFO] VERACODE UPLOAD AND SCAN'
         onExecute:
           - >-
             echo "onExecute is the main section where you would issue your build/test commands"
