Update verademoWorkflow.yml
added customizable input parameters to control the workflow

diff --git a/.github/workflows/verademoWorkflow.yml b/.github/workflows/verademoWorkflow.yml
--- a/.github/workflows/verademoWorkflow.yml
+++ b/.github/workflows/verademoWorkflow.yml
@@ -51,6 +51,18 @@ on:
                 - 'ubuntu-latest'
                 - 'macOs-latest'
                 - 'windows-latest'
+          Veracode-App-Name:
+            description: "Veracode App Profile Name"
+            required: false
+            default: '${{ github.repository }}'
+          Veracode-API-ID:
+            description: "Veracode API ID to use"
+            required: false
+            default: '${{ secrets.VERACODE_API_ID }}'
+          Veracode-API-Key:
+            description: "Veracode API Key to use"
+            required: false
+            default: '${{ secrets.VERACODE_API_KEY }}'
             
 env:
   SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
@@ -106,7 +118,7 @@ jobs:
           veracode package -a -d -s . -o .veracode/build/
           
       - name: Install the Veracode CLI ( macOs ) 
-        if: ${{ github.event.inputs.VeracodeCLI && ( github.event.inputs.Runner-Image == 'macOs-latest' )  }}
+        if: ${{ github.event.inputs.VeracodeCLI && ( github.event.inputs.Runner-Image == 'macOs-latest' ) && github.event.inputs.UsePM  }}
         run: |
           brew install veracode/tap/veracode-cli
           mkdir .veracode 
@@ -162,6 +174,53 @@ jobs:
       - run: |
           ls -la
           ls -la .veracode/build/
+
+      # Downloads the pipeline scanner jar directly for each of the operating systems and settings defined
+
+      - name: Veracode Pipeline Scan ( Java Wrapper ) [Windows no PM]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'windows-latest' ) && github.event.inputs.Run-Pipeline-Scan  && ( ! github.event.inputs.UsePM ) }}
+        run: |
+          wget https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
+          Expand-Archive -Path pipeline-scan-LATEST.zip -DestinationPath ./ -Force
+          ls
+          java -jar pipeline-scan.jar
+
+      # Installs the Veracode CLI fro the one that uses a package manager
+      - name: Veracode Pipeline Scan ( Java Wrapper ) [Windows PM]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'windows-latest' ) && github.event.inputs.Run-Pipeline-Scan  &&  github.event.inputs.UsePM  }}
+        run: |
+          choco install veracode-cli
+          veracode version
+          veracode static scan --help
+          
+      
+      - name: Veracode Pipeline Scan ( Java Wrapper ) [Ubuntu no PM]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'ubuntu-latest' ) && github.event.inputs.Run-Pipeline-Scan  }}
+        run: |
+          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
+          unzip -o pipeline-scan-LATEST.zip
+          ls -la
+          java -jar pipeline-scan.jar
+
+          
+      - name: Veracode Pipeline Scan ( Java Wrapper ) [MacOs PM]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'macOs-latest' ) && github.event.inputs.Run-Pipeline-Scan  &&  github.event.inputs.UsePM  }}
+        run: |
+          brew install veracode/tap/veracode-cli
+          veracode version
+          veracode static scan --help
+
+
+      - name: Veracode Pipeline Scan ( Java Wrapper ) [MacOs no PM]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'macOs-latest' ) && github.event.inputs.Run-Pipeline-Scan  && ( ! github.event.inputs.UsePM ) }}
+        run: |
+          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
+          unzip -o pipeline-scan-LATEST.zip
+          ls -la
+          java -jar pipeline-scan.jar
+      
+      
+          
           
       - name: Veracode Pipeline-Scan
         if: ${{ github.event.inputs.UseActions && github.event.inputs.Run-Pipeline-Scan }}
@@ -232,8 +291,72 @@ jobs:
             # Enter a case-sensitive, comma-separated list of name patterns that represent the names of the modules to scan as top-level modules. Veracode identifies these modules during prescan. The * wildcard matches zero or more characters. The ? wildcard matches exactly one character. For example, to include various module names that contain module: --include "module 1, module-*, module2.jar". The scan results show the names of the modules that Veracode identified and the modules included in the scan. This parameter does not pause, stop, or impact the performance of your pipeline.
             # include: # optional
               
+      - name: Veracode Upload and Scan ( Java API Wrapper ) [windows]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'windows-latest' ) && github.event.inputs.Run-Upload-and-Scan }}
+        run: |
+          ﻿Write-Output "Downloading the latest version of the Veracode Java API"
+          $versionstring = curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | findstr /r "latest";
+          $version = $versionstring.Trim() -replace '<latest>', '' -replace '</latest>', '';
+          
+          if( Test-Path .\wrapperVersion.txt -PathType leaf){
+          
+              $instVersion = cat .\wrapperVersion.txt
+          
+          
+              if($version -ne $instVersion){
+                  echo $version > wrapperVersion.txt
+                  curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$version/vosp-api-wrappers-java-$version-dist.zip -o java-wrapper-$version.zip
+                  mkdir java-wrapper-$version/
+                  Expand-Archive -Path java-wrapper-$version.zip -DestinationPath ./java-wrapper-$version/ -Force
+                  Copy-Item -Path ./java-wrapper-$version/VeracodeJavaAPI.jar -Destination ./ -Force
+              }
+              else {
+                  Write-Output "The latest version is currently installed";
+              }
+          }
+          else{
+              echo $version > wrapperVersion.txt
+              curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$version/vosp-api-wrappers-java-$version-dist.zip -o java-wrapper-$version.zip
+              mkdir java-wrapper-$version/
+              Expand-Archive -Path java-wrapper-$version.zip -DestinationPath ./java-wrapper-$version/ -Force
+              Copy-Item -Path ./java-wrapper-$version/VeracodeJavaAPI.jar -Destination ./ -Force
+          }
+          ls
+          java -jar VeracodeJavaAPI.jar -action uploadandscan -filepath .veracode/build/ -appname '${{ github.event.inputs.Veracode-App-Name }}' -createprofile true1 -version '${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}' -deleteincompletescan 
+          
 
-      
+      - name: Veracode Upload and Scan ( Java API Wrapper ) [ubuntu]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'ubuntu-latest' ) && github.event.inputs.Run-Upload-and-Scan }}
+        run: |
+            echo "Downloading the latest version of the Veracode Java API Wrapper"
+            WRAPPER_VERSION=`curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1`
+            if `wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar`; then
+                chmod 755 VeracodeJavaAPI.jar
+                echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
+            else
+                echo '[ERROR] DOWNLOAD FAILED'122w
+                exit 1
+            fi
+            ls
+            java -jar VeracodeJavaAPI.jar -action uploadandscan -filepath .veracode/build/ -appname '${{ github.event.inputs.Veracode-App-Name }}' -createprofile true1 -version '${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}' -deleteincompletescan 
+            
+            
+
+      - name: Veracode Upload and Scan ( Java API Wrapper ) [macOs]
+        if: ${{  ( ! github.event.inputs.UseActions ) &&  ( github.event.inputs.Runner-Image == 'macOs-latest' ) && github.event.inputs.Run-Upload-and-Scan }}
+        run: |
+            echo "Downloading the latest version of the Veracode Java API Wrapper"
+            WRAPPER_VERSION=`curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | grep latest |  cut -d '>' -f 2 | cut -d '<' -f 1`
+            if `wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$WRAPPER_VERSION/vosp-api-wrappers-java-$WRAPPER_VERSION.jar -O VeracodeJavaAPI.jar`; then
+                chmod 755 VeracodeJavaAPI.jar
+                echo '[INFO] SUCCESSFULLY DOWNLOADED WRAPPER'
+            else
+                echo '[ERROR] DOWNLOAD FAILED'122w
+                exit 1
+            fi
+            ls
+            java -jar VeracodeJavaAPI.jar -action uploadandscan -filepath .veracode/build/ -appname '${{ github.event.inputs.Veracode-App-Name }}' -createprofile true1 -version '${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}' -deleteincompletescan 
+        
       - name: Veracode Upload And Scan
         if: ${{ github.event.inputs.UseActions &&  github.event.inputs.Run-Upload-and-Scan }}
         # You may pin to the exact commit or the version.
@@ -241,11 +364,11 @@ jobs:
         uses: veracode/veracode-uploadandscan-action@0.2.4
         with:
           # appname
-          appname: Verademo
+          appname: ${{ github.event.inputs.Veracode-App-Name }}
           # createprofile
-          createprofile: false # default is true
+          createprofile: true # default is true
           # filepath
-          filepath: analysis/verademo.war
+          filepath: .veracode/build/
           # version
           version:  ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} # default is Scan from Github job: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
           # vid
